services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free

jobs:
  - name: daily-sync-job
    type: cron
    env: python
    schedule: "daily"  # או "0 6 * * *" כדי לקבוע שעה מדויקת
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/sync_sheet_to_sql.py
    plan: free
